/**
 * TypeScript client for the escrow program — deposit / release / refund.
 *
 * This is how the agent flow would use escrow instead of a direct transfer: the buyer **deposits**
 * for an order keyed by its Solana Pay `reference`; the seller is paid only when the buyer
 * **releases** (after delivery); the buyer can **refund** after the deadline. The `reference` is the
 * exact same key the seller already mints per request — so escrow drops into the existing protocol.
 *
 * Requires `anchor build` first (generates `../target/types/escrow.ts` + the IDL).
 */
import * as anchor from '@coral-xyz/anchor'
import { Program, BN } from '@coral-xyz/anchor'
import { PublicKey, Keypair, LAMPORTS_PER_SOL } from '@solana/web3.js'
import { ASSOCIATED_TOKEN_PROGRAM_ID, TOKEN_PROGRAM_ID, getAssociatedTokenAddressSync } from '@solana/spl-token'
// import type { Escrow } from '../target/types/escrow'   // generated by `anchor build`

// Deployed to devnet (anchor deploy). Run `anchor keys sync` after a fresh build to set your own.
export const PROGRAM_ID = new PublicKey('R5NWNg9eRLWWQU81Xbzz5Du1k7jTDeeT92Ty6qCeXet')

/** Derive the per-order escrow PDA: one per (buyer, reference). */
export function escrowPda(buyer: PublicKey, reference: PublicKey): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('escrow'), buyer.toBuffer(), reference.toBuffer()],
    PROGRAM_ID,
  )[0]
}

/** Derive the per-order SPL escrow PDA: one per (buyer, reference), distinct from the SOL PDA. */
export function escrowSplPda(buyer: PublicKey, reference: PublicKey): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('escrow_spl'), buyer.toBuffer(), reference.toBuffer()],
    PROGRAM_ID,
  )[0]
}

/** Buyer deposits `amountSol` for `reference`, refundable `deadlineSecs` from now. */
export async function deposit(
  program: Program<any>,
  buyer: Keypair,
  seller: PublicKey,
  reference: PublicKey,
  amountSol: number,
  deadlineSecs: number,
): Promise<string> {
  const deadline = new BN(Math.floor(Date.now() / 1000) + deadlineSecs)
  return program.methods
    .initialize(new BN(Math.round(amountSol * LAMPORTS_PER_SOL)), reference, deadline)
    .accounts({ buyer: buyer.publicKey, seller, escrow: escrowPda(buyer.publicKey, reference) })
    .signers([buyer])
    .rpc()
}

/** Buyer confirms delivery → pay the seller and close the escrow. */
export async function release(
  program: Program<any>,
  buyer: Keypair,
  seller: PublicKey,
  reference: PublicKey,
): Promise<string> {
  return program.methods
    .release()
    .accounts({ buyer: buyer.publicKey, seller, escrow: escrowPda(buyer.publicKey, reference) })
    .signers([buyer])
    .rpc()
}

/**
 * Seller-side check: does a funded escrow exist for `(buyer, reference)` naming `seller`, holding at
 * least `minAmountSol`? The seller calls this before delivering — "is there money locked for me?" —
 * replacing the direct-transfer `verifyPayment` in the escrow settlement path. Returns false if the
 * PDA doesn't exist, the parties don't match, or it's underfunded.
 */
export async function isFunded(
  program: Program<any>,
  buyer: PublicKey,
  seller: PublicKey,
  reference: PublicKey,
  minAmountSol = 0,
): Promise<boolean> {
  const acct = await (program.account as any).escrow.fetchNullable(escrowPda(buyer, reference))
  if (!acct) return false
  const partiesOk = acct.buyer.equals(buyer) && acct.seller.equals(seller)
  const amountOk = acct.amount.toNumber() >= Math.round(minAmountSol * LAMPORTS_PER_SOL)
  return partiesOk && amountOk
}

/** Buyer reclaims the deposit after the deadline (seller never delivered). */
export async function refund(
  program: Program<any>,
  buyer: Keypair,
  reference: PublicKey,
): Promise<string> {
  return program.methods
    .refund()
    .accounts({ buyer: buyer.publicKey, escrow: escrowPda(buyer.publicKey, reference) })
    .signers([buyer])
    .rpc()
}

// --- SPL-token escrow (same lifecycle, an EscrowSpl account under a distinct `escrow_spl` PDA) ---

async function mintDecimals(program: Program<any>, mint: PublicKey): Promise<number> {
  const { getMint } = await import('@solana/spl-token')
  return (await getMint(program.provider.connection, mint)).decimals
}

/** Buyer deposits `amount` of `mint` for `reference`, refundable `deadlineSecs` from now. */
export async function depositSpl(
  program: Program<any>,
  buyer: Keypair,
  seller: PublicKey,
  mint: PublicKey,
  reference: PublicKey,
  amount: number,
  deadlineSecs: number,
): Promise<string> {
  const decimals = await mintDecimals(program, mint)
  const escrow = escrowSplPda(buyer.publicKey, reference)
  const deadline = new BN(Math.floor(Date.now() / 1000) + deadlineSecs)
  return program.methods
    .initializeSpl(new BN(Math.round(amount * 10 ** decimals)), reference, deadline)
    .accounts({
      buyer: buyer.publicKey,
      seller,
      mint,
      escrow,
      buyerAta: getAssociatedTokenAddressSync(mint, buyer.publicKey),
      escrowAta: getAssociatedTokenAddressSync(mint, escrow, true),
      tokenProgram: TOKEN_PROGRAM_ID,
      associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
    })
    .signers([buyer])
    .rpc()
}

/** Buyer confirms delivery → pay the seller (transfer_checked) and close the SPL escrow. */
export async function releaseSpl(
  program: Program<any>,
  buyer: Keypair,
  seller: PublicKey,
  mint: PublicKey,
  reference: PublicKey,
): Promise<string> {
  const escrow = escrowSplPda(buyer.publicKey, reference)
  return program.methods
    .releaseSpl()
    .accounts({
      buyer: buyer.publicKey,
      seller,
      mint,
      escrow,
      escrowAta: getAssociatedTokenAddressSync(mint, escrow, true),
      sellerAta: getAssociatedTokenAddressSync(mint, seller),
      tokenProgram: TOKEN_PROGRAM_ID,
      associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
    })
    .signers([buyer])
    .rpc()
}

/** Seller-side check, SPL analog of `isFunded`: does a funded `EscrowSpl` exist for `(buyer, reference)`? */
export async function isFundedSpl(
  program: Program<any>,
  buyer: PublicKey,
  seller: PublicKey,
  mint: PublicKey,
  reference: PublicKey,
  minAmount = 0,
): Promise<boolean> {
  const acct = await (program.account as any).escrowSpl.fetchNullable(escrowSplPda(buyer, reference))
  if (!acct) return false
  const decimals = await mintDecimals(program, mint)
  const partiesOk = acct.buyer.equals(buyer) && acct.seller.equals(seller) && acct.mint.equals(mint)
  const amountOk = acct.amount.toNumber() >= Math.round(minAmount * 10 ** decimals)
  return partiesOk && amountOk
}

/** Buyer reclaims the SPL deposit after the deadline (seller never delivered). */
export async function refundSpl(
  program: Program<any>,
  buyer: Keypair,
  mint: PublicKey,
  reference: PublicKey,
): Promise<string> {
  const escrow = escrowSplPda(buyer.publicKey, reference)
  return program.methods
    .refundSpl()
    .accounts({
      buyer: buyer.publicKey,
      mint,
      escrow,
      escrowAta: getAssociatedTokenAddressSync(mint, escrow, true),
      buyerAta: getAssociatedTokenAddressSync(mint, buyer.publicKey),
      tokenProgram: TOKEN_PROGRAM_ID,
    })
    .signers([buyer])
    .rpc()
}
